name: nota_note
description: "NotaNote는 노션, 클러버코드, 릴리스AI, 위키피디아 등의 다양한 장점을 섞어 만든 메모장 앱입니다."

publish_to: "none"

version: 1.0.8+9

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sentry_flutter: ^9.1.0

  kakao_flutter_sdk: ^1.9.7+3
  flutter_sound: ^9.28.0
  audioplayers: ^6.4.0
  cupertino_rrect: ^0.0.2
  path_provider: ^2.1.0
  sqflite: ^2.4.2
  uuid: ^4.5.1
  path: ^1.9.1
  permission_handler: ^12.0.0+1
  kakao_flutter_sdk_user: ^1.9.7+3
  flutter_keyboard_visibility: ^6.0.0
  http: ^1.4.0
  firebase_core: ^3.13.1
  flutter_dotenv: ^5.2.1
  firebase_auth: ^5.5.4
  font_awesome_flutter: 10.8.0
  share_plus: ^11.0.0
  flutter_svg: ^2.1.0
  flutter_quill: ^11.4.1
  flutter_quill_extensions: ^11.0.0
  firebase_analytics: ^11.4.6
  firebase_storage: ^12.4.7
  google_mobile_ads: ^6.0.0
  cloud_firestore: ^5.6.8
  flutter_riverpod: ^2.6.1
  cupertino_icons: ^1.0.8
  firebase_crashlytics: ^4.3.7
  google_sign_in: ^6.3.0
  crypto: ^3.0.6
  logger: ^2.5.0
  image_picker: ^1.1.2
  sign_in_with_apple: ^7.0.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_markdown: ^0.7.7+1
  dart_jsonwebtoken: ^3.1.1
  flutter_local_notifications: ^18.0.0+1

  basic_utils: ^5.7.0
  pointycastle: ^3.9.1
  package_info_plus: ^8.3.0
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env
    - assets/images/font_size.png
    - assets/
    - assets/images/
    - assets/icons/
    - assets/terms/terms_of_service.md
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
