name: nota_note
description: "NotaNote는 노션, 클러버코드, 릴리스AI, 위키피디아 등의 다양한 장점을 섞어 만든 메모장 앱입니다."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  kakao_flutter_sdk: ^1.9.7+3
  flutter_sound: ^9.28.0
  audioplayers: ^6.4.0
  cupertino_rrect: ^0.0.2
  path_provider: ^2.1.0
  sqflite: ^2.4.2
  path: ^1.9.1
  permission_handler: ^12.0.0+1
  kakao_flutter_sdk_user: ^1.9.7+3
  flutter_keyboard_visibility: ^6.0.0
  http: ^1.4.0
  firebase_core: ^3.13.1
  flutter_dotenv: ^5.2.1
  firebase_auth: ^5.5.4
  font_awesome_flutter: 10.8.0
  share_plus: ^11.0.0
  flutter_svg: ^2.1.0
  flutter_quill: ^11.4.1
  flutter_quill_extensions: ^11.0.0
  firebase_analytics: ^11.4.6
  firebase_storage: ^12.4.6
  cloud_firestore: ^5.6.8
  flutter_riverpod: ^2.6.1
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.3.0
  crypto: ^3.0.6
  image_picker: ^1.1.2
  sign_in_with_apple: ^7.0.1
  timeago: ^3.7.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env
    - assets/images/font_size.png
    - assets/
    - assets/images/
    - assets/icons/
  uses-material-design: true
